language: php
php:
  - hhvm
before_script:
- sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
- cp test_services.json.dist test_services.json
- composer install --dev
script: vendor/bin/phpunit
